services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: trang_vien_so
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST_AUTH_METHOD: md5
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d trang_vien_so"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s



volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge